name: Tests

on:
  push:
    branches: ["feat/*", "dev", "main"]
    paths-ignore:
      - "docs/**"

  pull_request:
    branches: ["main", "dev"]
    paths-ignore:
      - "docs/**"

jobs:
  test:
    name: "ğŸ§ª Test: (Node: ${{ matrix.node-version }})"
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ğŸ“¦ Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: â” Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: "pnpm"

      - name: ğŸ“¥ Install deps
        run: pnpm i --frozen-lockfile

      - name: ğŸ— Build
        run: pnpm build

      - name: ğŸ§ª Run tests
        run: pnpm test:cov

      - name: Check bundle size
        run: pnpm size
